# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.9.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.9.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/daniel.almeida/Personal/ArbutusEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/daniel.almeida/Personal/ArbutusEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.9.4/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.9.4/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/daniel.almeida/Personal/ArbutusEngine/CMakeFiles /Users/daniel.almeida/Personal/ArbutusEngine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/daniel.almeida/Personal/ArbutusEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ArbutusEngine

# Build rule for target.
ArbutusEngine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ArbutusEngine
.PHONY : ArbutusEngine

# fast build rule for target.
ArbutusEngine/fast:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/build
.PHONY : ArbutusEngine/fast

src/Apps/Server/Messages.o: src/Apps/Server/Messages.cpp.o

.PHONY : src/Apps/Server/Messages.o

# target to build an object file
src/Apps/Server/Messages.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Apps/Server/Messages.cpp.o
.PHONY : src/Apps/Server/Messages.cpp.o

src/Apps/Server/Messages.i: src/Apps/Server/Messages.cpp.i

.PHONY : src/Apps/Server/Messages.i

# target to preprocess a source file
src/Apps/Server/Messages.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Apps/Server/Messages.cpp.i
.PHONY : src/Apps/Server/Messages.cpp.i

src/Apps/Server/Messages.s: src/Apps/Server/Messages.cpp.s

.PHONY : src/Apps/Server/Messages.s

# target to generate assembly for a file
src/Apps/Server/Messages.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Apps/Server/Messages.cpp.s
.PHONY : src/Apps/Server/Messages.cpp.s

src/Apps/Server/main.o: src/Apps/Server/main.cpp.o

.PHONY : src/Apps/Server/main.o

# target to build an object file
src/Apps/Server/main.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Apps/Server/main.cpp.o
.PHONY : src/Apps/Server/main.cpp.o

src/Apps/Server/main.i: src/Apps/Server/main.cpp.i

.PHONY : src/Apps/Server/main.i

# target to preprocess a source file
src/Apps/Server/main.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Apps/Server/main.cpp.i
.PHONY : src/Apps/Server/main.cpp.i

src/Apps/Server/main.s: src/Apps/Server/main.cpp.s

.PHONY : src/Apps/Server/main.s

# target to generate assembly for a file
src/Apps/Server/main.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Apps/Server/main.cpp.s
.PHONY : src/Apps/Server/main.cpp.s

src/Apps/Server/ofApp.o: src/Apps/Server/ofApp.cpp.o

.PHONY : src/Apps/Server/ofApp.o

# target to build an object file
src/Apps/Server/ofApp.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Apps/Server/ofApp.cpp.o
.PHONY : src/Apps/Server/ofApp.cpp.o

src/Apps/Server/ofApp.i: src/Apps/Server/ofApp.cpp.i

.PHONY : src/Apps/Server/ofApp.i

# target to preprocess a source file
src/Apps/Server/ofApp.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Apps/Server/ofApp.cpp.i
.PHONY : src/Apps/Server/ofApp.cpp.i

src/Apps/Server/ofApp.s: src/Apps/Server/ofApp.cpp.s

.PHONY : src/Apps/Server/ofApp.s

# target to generate assembly for a file
src/Apps/Server/ofApp.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Apps/Server/ofApp.cpp.s
.PHONY : src/Apps/Server/ofApp.cpp.s

src/CatchCpp/Engine.o: src/CatchCpp/Engine.cpp.o

.PHONY : src/CatchCpp/Engine.o

# target to build an object file
src/CatchCpp/Engine.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/Engine.cpp.o
.PHONY : src/CatchCpp/Engine.cpp.o

src/CatchCpp/Engine.i: src/CatchCpp/Engine.cpp.i

.PHONY : src/CatchCpp/Engine.i

# target to preprocess a source file
src/CatchCpp/Engine.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/Engine.cpp.i
.PHONY : src/CatchCpp/Engine.cpp.i

src/CatchCpp/Engine.s: src/CatchCpp/Engine.cpp.s

.PHONY : src/CatchCpp/Engine.s

# target to generate assembly for a file
src/CatchCpp/Engine.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/Engine.cpp.s
.PHONY : src/CatchCpp/Engine.cpp.s

src/CatchCpp/FileHandling/JsonLoadTest.o: src/CatchCpp/FileHandling/JsonLoadTest.cpp.o

.PHONY : src/CatchCpp/FileHandling/JsonLoadTest.o

# target to build an object file
src/CatchCpp/FileHandling/JsonLoadTest.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/FileHandling/JsonLoadTest.cpp.o
.PHONY : src/CatchCpp/FileHandling/JsonLoadTest.cpp.o

src/CatchCpp/FileHandling/JsonLoadTest.i: src/CatchCpp/FileHandling/JsonLoadTest.cpp.i

.PHONY : src/CatchCpp/FileHandling/JsonLoadTest.i

# target to preprocess a source file
src/CatchCpp/FileHandling/JsonLoadTest.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/FileHandling/JsonLoadTest.cpp.i
.PHONY : src/CatchCpp/FileHandling/JsonLoadTest.cpp.i

src/CatchCpp/FileHandling/JsonLoadTest.s: src/CatchCpp/FileHandling/JsonLoadTest.cpp.s

.PHONY : src/CatchCpp/FileHandling/JsonLoadTest.s

# target to generate assembly for a file
src/CatchCpp/FileHandling/JsonLoadTest.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/FileHandling/JsonLoadTest.cpp.s
.PHONY : src/CatchCpp/FileHandling/JsonLoadTest.cpp.s

src/CatchCpp/FileHandling/JsonSaveTest.o: src/CatchCpp/FileHandling/JsonSaveTest.cpp.o

.PHONY : src/CatchCpp/FileHandling/JsonSaveTest.o

# target to build an object file
src/CatchCpp/FileHandling/JsonSaveTest.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/FileHandling/JsonSaveTest.cpp.o
.PHONY : src/CatchCpp/FileHandling/JsonSaveTest.cpp.o

src/CatchCpp/FileHandling/JsonSaveTest.i: src/CatchCpp/FileHandling/JsonSaveTest.cpp.i

.PHONY : src/CatchCpp/FileHandling/JsonSaveTest.i

# target to preprocess a source file
src/CatchCpp/FileHandling/JsonSaveTest.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/FileHandling/JsonSaveTest.cpp.i
.PHONY : src/CatchCpp/FileHandling/JsonSaveTest.cpp.i

src/CatchCpp/FileHandling/JsonSaveTest.s: src/CatchCpp/FileHandling/JsonSaveTest.cpp.s

.PHONY : src/CatchCpp/FileHandling/JsonSaveTest.s

# target to generate assembly for a file
src/CatchCpp/FileHandling/JsonSaveTest.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/FileHandling/JsonSaveTest.cpp.s
.PHONY : src/CatchCpp/FileHandling/JsonSaveTest.cpp.s

src/CatchCpp/Layer.o: src/CatchCpp/Layer.cpp.o

.PHONY : src/CatchCpp/Layer.o

# target to build an object file
src/CatchCpp/Layer.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/Layer.cpp.o
.PHONY : src/CatchCpp/Layer.cpp.o

src/CatchCpp/Layer.i: src/CatchCpp/Layer.cpp.i

.PHONY : src/CatchCpp/Layer.i

# target to preprocess a source file
src/CatchCpp/Layer.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/Layer.cpp.i
.PHONY : src/CatchCpp/Layer.cpp.i

src/CatchCpp/Layer.s: src/CatchCpp/Layer.cpp.s

.PHONY : src/CatchCpp/Layer.s

# target to generate assembly for a file
src/CatchCpp/Layer.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/Layer.cpp.s
.PHONY : src/CatchCpp/Layer.cpp.s

src/CatchCpp/LayerProperties.o: src/CatchCpp/LayerProperties.cpp.o

.PHONY : src/CatchCpp/LayerProperties.o

# target to build an object file
src/CatchCpp/LayerProperties.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/LayerProperties.cpp.o
.PHONY : src/CatchCpp/LayerProperties.cpp.o

src/CatchCpp/LayerProperties.i: src/CatchCpp/LayerProperties.cpp.i

.PHONY : src/CatchCpp/LayerProperties.i

# target to preprocess a source file
src/CatchCpp/LayerProperties.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/LayerProperties.cpp.i
.PHONY : src/CatchCpp/LayerProperties.cpp.i

src/CatchCpp/LayerProperties.s: src/CatchCpp/LayerProperties.cpp.s

.PHONY : src/CatchCpp/LayerProperties.s

# target to generate assembly for a file
src/CatchCpp/LayerProperties.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/LayerProperties.cpp.s
.PHONY : src/CatchCpp/LayerProperties.cpp.s

src/CatchCpp/Properties/PropertiesTest.o: src/CatchCpp/Properties/PropertiesTest.cpp.o

.PHONY : src/CatchCpp/Properties/PropertiesTest.o

# target to build an object file
src/CatchCpp/Properties/PropertiesTest.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/Properties/PropertiesTest.cpp.o
.PHONY : src/CatchCpp/Properties/PropertiesTest.cpp.o

src/CatchCpp/Properties/PropertiesTest.i: src/CatchCpp/Properties/PropertiesTest.cpp.i

.PHONY : src/CatchCpp/Properties/PropertiesTest.i

# target to preprocess a source file
src/CatchCpp/Properties/PropertiesTest.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/Properties/PropertiesTest.cpp.i
.PHONY : src/CatchCpp/Properties/PropertiesTest.cpp.i

src/CatchCpp/Properties/PropertiesTest.s: src/CatchCpp/Properties/PropertiesTest.cpp.s

.PHONY : src/CatchCpp/Properties/PropertiesTest.s

# target to generate assembly for a file
src/CatchCpp/Properties/PropertiesTest.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/Properties/PropertiesTest.cpp.s
.PHONY : src/CatchCpp/Properties/PropertiesTest.cpp.s

src/CatchCpp/Properties/VisualInstancesPropertiesTest.o: src/CatchCpp/Properties/VisualInstancesPropertiesTest.cpp.o

.PHONY : src/CatchCpp/Properties/VisualInstancesPropertiesTest.o

# target to build an object file
src/CatchCpp/Properties/VisualInstancesPropertiesTest.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/Properties/VisualInstancesPropertiesTest.cpp.o
.PHONY : src/CatchCpp/Properties/VisualInstancesPropertiesTest.cpp.o

src/CatchCpp/Properties/VisualInstancesPropertiesTest.i: src/CatchCpp/Properties/VisualInstancesPropertiesTest.cpp.i

.PHONY : src/CatchCpp/Properties/VisualInstancesPropertiesTest.i

# target to preprocess a source file
src/CatchCpp/Properties/VisualInstancesPropertiesTest.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/Properties/VisualInstancesPropertiesTest.cpp.i
.PHONY : src/CatchCpp/Properties/VisualInstancesPropertiesTest.cpp.i

src/CatchCpp/Properties/VisualInstancesPropertiesTest.s: src/CatchCpp/Properties/VisualInstancesPropertiesTest.cpp.s

.PHONY : src/CatchCpp/Properties/VisualInstancesPropertiesTest.s

# target to generate assembly for a file
src/CatchCpp/Properties/VisualInstancesPropertiesTest.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/Properties/VisualInstancesPropertiesTest.cpp.s
.PHONY : src/CatchCpp/Properties/VisualInstancesPropertiesTest.cpp.s

src/CatchCpp/Scene.o: src/CatchCpp/Scene.cpp.o

.PHONY : src/CatchCpp/Scene.o

# target to build an object file
src/CatchCpp/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/Scene.cpp.o
.PHONY : src/CatchCpp/Scene.cpp.o

src/CatchCpp/Scene.i: src/CatchCpp/Scene.cpp.i

.PHONY : src/CatchCpp/Scene.i

# target to preprocess a source file
src/CatchCpp/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/Scene.cpp.i
.PHONY : src/CatchCpp/Scene.cpp.i

src/CatchCpp/Scene.s: src/CatchCpp/Scene.cpp.s

.PHONY : src/CatchCpp/Scene.s

# target to generate assembly for a file
src/CatchCpp/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/Scene.cpp.s
.PHONY : src/CatchCpp/Scene.cpp.s

src/CatchCpp/Server/messages.o: src/CatchCpp/Server/messages.cpp.o

.PHONY : src/CatchCpp/Server/messages.o

# target to build an object file
src/CatchCpp/Server/messages.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/Server/messages.cpp.o
.PHONY : src/CatchCpp/Server/messages.cpp.o

src/CatchCpp/Server/messages.i: src/CatchCpp/Server/messages.cpp.i

.PHONY : src/CatchCpp/Server/messages.i

# target to preprocess a source file
src/CatchCpp/Server/messages.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/Server/messages.cpp.i
.PHONY : src/CatchCpp/Server/messages.cpp.i

src/CatchCpp/Server/messages.s: src/CatchCpp/Server/messages.cpp.s

.PHONY : src/CatchCpp/Server/messages.s

# target to generate assembly for a file
src/CatchCpp/Server/messages.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/Server/messages.cpp.s
.PHONY : src/CatchCpp/Server/messages.cpp.s

src/CatchCpp/SizeProperties.o: src/CatchCpp/SizeProperties.cpp.o

.PHONY : src/CatchCpp/SizeProperties.o

# target to build an object file
src/CatchCpp/SizeProperties.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/SizeProperties.cpp.o
.PHONY : src/CatchCpp/SizeProperties.cpp.o

src/CatchCpp/SizeProperties.i: src/CatchCpp/SizeProperties.cpp.i

.PHONY : src/CatchCpp/SizeProperties.i

# target to preprocess a source file
src/CatchCpp/SizeProperties.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/SizeProperties.cpp.i
.PHONY : src/CatchCpp/SizeProperties.cpp.i

src/CatchCpp/SizeProperties.s: src/CatchCpp/SizeProperties.cpp.s

.PHONY : src/CatchCpp/SizeProperties.s

# target to generate assembly for a file
src/CatchCpp/SizeProperties.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/SizeProperties.cpp.s
.PHONY : src/CatchCpp/SizeProperties.cpp.s

src/CatchCpp/UtilsTests.o: src/CatchCpp/UtilsTests.cpp.o

.PHONY : src/CatchCpp/UtilsTests.o

# target to build an object file
src/CatchCpp/UtilsTests.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/UtilsTests.cpp.o
.PHONY : src/CatchCpp/UtilsTests.cpp.o

src/CatchCpp/UtilsTests.i: src/CatchCpp/UtilsTests.cpp.i

.PHONY : src/CatchCpp/UtilsTests.i

# target to preprocess a source file
src/CatchCpp/UtilsTests.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/UtilsTests.cpp.i
.PHONY : src/CatchCpp/UtilsTests.cpp.i

src/CatchCpp/UtilsTests.s: src/CatchCpp/UtilsTests.cpp.s

.PHONY : src/CatchCpp/UtilsTests.s

# target to generate assembly for a file
src/CatchCpp/UtilsTests.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/UtilsTests.cpp.s
.PHONY : src/CatchCpp/UtilsTests.cpp.s

src/CatchCpp/Visuals.o: src/CatchCpp/Visuals.cpp.o

.PHONY : src/CatchCpp/Visuals.o

# target to build an object file
src/CatchCpp/Visuals.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/Visuals.cpp.o
.PHONY : src/CatchCpp/Visuals.cpp.o

src/CatchCpp/Visuals.i: src/CatchCpp/Visuals.cpp.i

.PHONY : src/CatchCpp/Visuals.i

# target to preprocess a source file
src/CatchCpp/Visuals.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/Visuals.cpp.i
.PHONY : src/CatchCpp/Visuals.cpp.i

src/CatchCpp/Visuals.s: src/CatchCpp/Visuals.cpp.s

.PHONY : src/CatchCpp/Visuals.s

# target to generate assembly for a file
src/CatchCpp/Visuals.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/Visuals.cpp.s
.PHONY : src/CatchCpp/Visuals.cpp.s

src/CatchCpp/main.o: src/CatchCpp/main.cpp.o

.PHONY : src/CatchCpp/main.o

# target to build an object file
src/CatchCpp/main.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/main.cpp.o
.PHONY : src/CatchCpp/main.cpp.o

src/CatchCpp/main.i: src/CatchCpp/main.cpp.i

.PHONY : src/CatchCpp/main.i

# target to preprocess a source file
src/CatchCpp/main.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/main.cpp.i
.PHONY : src/CatchCpp/main.cpp.i

src/CatchCpp/main.s: src/CatchCpp/main.cpp.s

.PHONY : src/CatchCpp/main.s

# target to generate assembly for a file
src/CatchCpp/main.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/main.cpp.s
.PHONY : src/CatchCpp/main.cpp.s

src/CatchCpp/ofApp.o: src/CatchCpp/ofApp.cpp.o

.PHONY : src/CatchCpp/ofApp.o

# target to build an object file
src/CatchCpp/ofApp.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/ofApp.cpp.o
.PHONY : src/CatchCpp/ofApp.cpp.o

src/CatchCpp/ofApp.i: src/CatchCpp/ofApp.cpp.i

.PHONY : src/CatchCpp/ofApp.i

# target to preprocess a source file
src/CatchCpp/ofApp.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/ofApp.cpp.i
.PHONY : src/CatchCpp/ofApp.cpp.i

src/CatchCpp/ofApp.s: src/CatchCpp/ofApp.cpp.s

.PHONY : src/CatchCpp/ofApp.s

# target to generate assembly for a file
src/CatchCpp/ofApp.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/CatchCpp/ofApp.cpp.s
.PHONY : src/CatchCpp/ofApp.cpp.s

src/Examples/Empty/main.o: src/Examples/Empty/main.cpp.o

.PHONY : src/Examples/Empty/main.o

# target to build an object file
src/Examples/Empty/main.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Examples/Empty/main.cpp.o
.PHONY : src/Examples/Empty/main.cpp.o

src/Examples/Empty/main.i: src/Examples/Empty/main.cpp.i

.PHONY : src/Examples/Empty/main.i

# target to preprocess a source file
src/Examples/Empty/main.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Examples/Empty/main.cpp.i
.PHONY : src/Examples/Empty/main.cpp.i

src/Examples/Empty/main.s: src/Examples/Empty/main.cpp.s

.PHONY : src/Examples/Empty/main.s

# target to generate assembly for a file
src/Examples/Empty/main.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Examples/Empty/main.cpp.s
.PHONY : src/Examples/Empty/main.cpp.s

src/Examples/Empty/ofApp.o: src/Examples/Empty/ofApp.cpp.o

.PHONY : src/Examples/Empty/ofApp.o

# target to build an object file
src/Examples/Empty/ofApp.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Examples/Empty/ofApp.cpp.o
.PHONY : src/Examples/Empty/ofApp.cpp.o

src/Examples/Empty/ofApp.i: src/Examples/Empty/ofApp.cpp.i

.PHONY : src/Examples/Empty/ofApp.i

# target to preprocess a source file
src/Examples/Empty/ofApp.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Examples/Empty/ofApp.cpp.i
.PHONY : src/Examples/Empty/ofApp.cpp.i

src/Examples/Empty/ofApp.s: src/Examples/Empty/ofApp.cpp.s

.PHONY : src/Examples/Empty/ofApp.s

# target to generate assembly for a file
src/Examples/Empty/ofApp.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Examples/Empty/ofApp.cpp.s
.PHONY : src/Examples/Empty/ofApp.cpp.s

src/Examples/HelloWorld/main.o: src/Examples/HelloWorld/main.cpp.o

.PHONY : src/Examples/HelloWorld/main.o

# target to build an object file
src/Examples/HelloWorld/main.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Examples/HelloWorld/main.cpp.o
.PHONY : src/Examples/HelloWorld/main.cpp.o

src/Examples/HelloWorld/main.i: src/Examples/HelloWorld/main.cpp.i

.PHONY : src/Examples/HelloWorld/main.i

# target to preprocess a source file
src/Examples/HelloWorld/main.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Examples/HelloWorld/main.cpp.i
.PHONY : src/Examples/HelloWorld/main.cpp.i

src/Examples/HelloWorld/main.s: src/Examples/HelloWorld/main.cpp.s

.PHONY : src/Examples/HelloWorld/main.s

# target to generate assembly for a file
src/Examples/HelloWorld/main.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Examples/HelloWorld/main.cpp.s
.PHONY : src/Examples/HelloWorld/main.cpp.s

src/Examples/HelloWorld/ofApp.o: src/Examples/HelloWorld/ofApp.cpp.o

.PHONY : src/Examples/HelloWorld/ofApp.o

# target to build an object file
src/Examples/HelloWorld/ofApp.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Examples/HelloWorld/ofApp.cpp.o
.PHONY : src/Examples/HelloWorld/ofApp.cpp.o

src/Examples/HelloWorld/ofApp.i: src/Examples/HelloWorld/ofApp.cpp.i

.PHONY : src/Examples/HelloWorld/ofApp.i

# target to preprocess a source file
src/Examples/HelloWorld/ofApp.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Examples/HelloWorld/ofApp.cpp.i
.PHONY : src/Examples/HelloWorld/ofApp.cpp.i

src/Examples/HelloWorld/ofApp.s: src/Examples/HelloWorld/ofApp.cpp.s

.PHONY : src/Examples/HelloWorld/ofApp.s

# target to generate assembly for a file
src/Examples/HelloWorld/ofApp.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Examples/HelloWorld/ofApp.cpp.s
.PHONY : src/Examples/HelloWorld/ofApp.cpp.s

src/Library/Engine/FileHandling/JsonLoad.o: src/Library/Engine/FileHandling/JsonLoad.cpp.o

.PHONY : src/Library/Engine/FileHandling/JsonLoad.o

# target to build an object file
src/Library/Engine/FileHandling/JsonLoad.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Library/Engine/FileHandling/JsonLoad.cpp.o
.PHONY : src/Library/Engine/FileHandling/JsonLoad.cpp.o

src/Library/Engine/FileHandling/JsonLoad.i: src/Library/Engine/FileHandling/JsonLoad.cpp.i

.PHONY : src/Library/Engine/FileHandling/JsonLoad.i

# target to preprocess a source file
src/Library/Engine/FileHandling/JsonLoad.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Library/Engine/FileHandling/JsonLoad.cpp.i
.PHONY : src/Library/Engine/FileHandling/JsonLoad.cpp.i

src/Library/Engine/FileHandling/JsonLoad.s: src/Library/Engine/FileHandling/JsonLoad.cpp.s

.PHONY : src/Library/Engine/FileHandling/JsonLoad.s

# target to generate assembly for a file
src/Library/Engine/FileHandling/JsonLoad.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Library/Engine/FileHandling/JsonLoad.cpp.s
.PHONY : src/Library/Engine/FileHandling/JsonLoad.cpp.s

src/Library/Engine/FileHandling/JsonSave.o: src/Library/Engine/FileHandling/JsonSave.cpp.o

.PHONY : src/Library/Engine/FileHandling/JsonSave.o

# target to build an object file
src/Library/Engine/FileHandling/JsonSave.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Library/Engine/FileHandling/JsonSave.cpp.o
.PHONY : src/Library/Engine/FileHandling/JsonSave.cpp.o

src/Library/Engine/FileHandling/JsonSave.i: src/Library/Engine/FileHandling/JsonSave.cpp.i

.PHONY : src/Library/Engine/FileHandling/JsonSave.i

# target to preprocess a source file
src/Library/Engine/FileHandling/JsonSave.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Library/Engine/FileHandling/JsonSave.cpp.i
.PHONY : src/Library/Engine/FileHandling/JsonSave.cpp.i

src/Library/Engine/FileHandling/JsonSave.s: src/Library/Engine/FileHandling/JsonSave.cpp.s

.PHONY : src/Library/Engine/FileHandling/JsonSave.s

# target to generate assembly for a file
src/Library/Engine/FileHandling/JsonSave.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Library/Engine/FileHandling/JsonSave.cpp.s
.PHONY : src/Library/Engine/FileHandling/JsonSave.cpp.s

src/Library/Engine/FileHandling/SetFile.o: src/Library/Engine/FileHandling/SetFile.cpp.o

.PHONY : src/Library/Engine/FileHandling/SetFile.o

# target to build an object file
src/Library/Engine/FileHandling/SetFile.cpp.o:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Library/Engine/FileHandling/SetFile.cpp.o
.PHONY : src/Library/Engine/FileHandling/SetFile.cpp.o

src/Library/Engine/FileHandling/SetFile.i: src/Library/Engine/FileHandling/SetFile.cpp.i

.PHONY : src/Library/Engine/FileHandling/SetFile.i

# target to preprocess a source file
src/Library/Engine/FileHandling/SetFile.cpp.i:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Library/Engine/FileHandling/SetFile.cpp.i
.PHONY : src/Library/Engine/FileHandling/SetFile.cpp.i

src/Library/Engine/FileHandling/SetFile.s: src/Library/Engine/FileHandling/SetFile.cpp.s

.PHONY : src/Library/Engine/FileHandling/SetFile.s

# target to generate assembly for a file
src/Library/Engine/FileHandling/SetFile.cpp.s:
	$(MAKE) -f CMakeFiles/ArbutusEngine.dir/build.make CMakeFiles/ArbutusEngine.dir/src/Library/Engine/FileHandling/SetFile.cpp.s
.PHONY : src/Library/Engine/FileHandling/SetFile.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ArbutusEngine"
	@echo "... src/Apps/Server/Messages.o"
	@echo "... src/Apps/Server/Messages.i"
	@echo "... src/Apps/Server/Messages.s"
	@echo "... src/Apps/Server/main.o"
	@echo "... src/Apps/Server/main.i"
	@echo "... src/Apps/Server/main.s"
	@echo "... src/Apps/Server/ofApp.o"
	@echo "... src/Apps/Server/ofApp.i"
	@echo "... src/Apps/Server/ofApp.s"
	@echo "... src/CatchCpp/Engine.o"
	@echo "... src/CatchCpp/Engine.i"
	@echo "... src/CatchCpp/Engine.s"
	@echo "... src/CatchCpp/FileHandling/JsonLoadTest.o"
	@echo "... src/CatchCpp/FileHandling/JsonLoadTest.i"
	@echo "... src/CatchCpp/FileHandling/JsonLoadTest.s"
	@echo "... src/CatchCpp/FileHandling/JsonSaveTest.o"
	@echo "... src/CatchCpp/FileHandling/JsonSaveTest.i"
	@echo "... src/CatchCpp/FileHandling/JsonSaveTest.s"
	@echo "... src/CatchCpp/Layer.o"
	@echo "... src/CatchCpp/Layer.i"
	@echo "... src/CatchCpp/Layer.s"
	@echo "... src/CatchCpp/LayerProperties.o"
	@echo "... src/CatchCpp/LayerProperties.i"
	@echo "... src/CatchCpp/LayerProperties.s"
	@echo "... src/CatchCpp/Properties/PropertiesTest.o"
	@echo "... src/CatchCpp/Properties/PropertiesTest.i"
	@echo "... src/CatchCpp/Properties/PropertiesTest.s"
	@echo "... src/CatchCpp/Properties/VisualInstancesPropertiesTest.o"
	@echo "... src/CatchCpp/Properties/VisualInstancesPropertiesTest.i"
	@echo "... src/CatchCpp/Properties/VisualInstancesPropertiesTest.s"
	@echo "... src/CatchCpp/Scene.o"
	@echo "... src/CatchCpp/Scene.i"
	@echo "... src/CatchCpp/Scene.s"
	@echo "... src/CatchCpp/Server/messages.o"
	@echo "... src/CatchCpp/Server/messages.i"
	@echo "... src/CatchCpp/Server/messages.s"
	@echo "... src/CatchCpp/SizeProperties.o"
	@echo "... src/CatchCpp/SizeProperties.i"
	@echo "... src/CatchCpp/SizeProperties.s"
	@echo "... src/CatchCpp/UtilsTests.o"
	@echo "... src/CatchCpp/UtilsTests.i"
	@echo "... src/CatchCpp/UtilsTests.s"
	@echo "... src/CatchCpp/Visuals.o"
	@echo "... src/CatchCpp/Visuals.i"
	@echo "... src/CatchCpp/Visuals.s"
	@echo "... src/CatchCpp/main.o"
	@echo "... src/CatchCpp/main.i"
	@echo "... src/CatchCpp/main.s"
	@echo "... src/CatchCpp/ofApp.o"
	@echo "... src/CatchCpp/ofApp.i"
	@echo "... src/CatchCpp/ofApp.s"
	@echo "... src/Examples/Empty/main.o"
	@echo "... src/Examples/Empty/main.i"
	@echo "... src/Examples/Empty/main.s"
	@echo "... src/Examples/Empty/ofApp.o"
	@echo "... src/Examples/Empty/ofApp.i"
	@echo "... src/Examples/Empty/ofApp.s"
	@echo "... src/Examples/HelloWorld/main.o"
	@echo "... src/Examples/HelloWorld/main.i"
	@echo "... src/Examples/HelloWorld/main.s"
	@echo "... src/Examples/HelloWorld/ofApp.o"
	@echo "... src/Examples/HelloWorld/ofApp.i"
	@echo "... src/Examples/HelloWorld/ofApp.s"
	@echo "... src/Library/Engine/FileHandling/JsonLoad.o"
	@echo "... src/Library/Engine/FileHandling/JsonLoad.i"
	@echo "... src/Library/Engine/FileHandling/JsonLoad.s"
	@echo "... src/Library/Engine/FileHandling/JsonSave.o"
	@echo "... src/Library/Engine/FileHandling/JsonSave.i"
	@echo "... src/Library/Engine/FileHandling/JsonSave.s"
	@echo "... src/Library/Engine/FileHandling/SetFile.o"
	@echo "... src/Library/Engine/FileHandling/SetFile.i"
	@echo "... src/Library/Engine/FileHandling/SetFile.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

